#  base image
FROM postgres:11.2-alpine

WORKDIR /
# run create.sql on init
ADD ./create.sql /docker-entrypoint-initdb.d



#USER postgres

#COPY ./fichas_dina.bak /fichas_dina.bak
COPY ./fichas_dina.dump /fichas_dina.dump


COPY ./restore_database.sh /restore_database.sh
RUN chmod +x /restore_database.sh

#CMD ["psql fichas_dina < fichas_dina.dump"]
#CMD ["psql", "fichas_dina < /user/src/database/fichas_dina.dump"]
CMD ["/restore_database.sh"]
#CMD ["pg_restore", "-d fichas_dina /user/src/database/fichas_dina.bak"]
