version: "3.7"

services:
        #map:
        #build:
        # context: ./services/map
        #   dockerfile: Dockerfile
        #ports:
        #- 80:9080

  client:
    build:
           context: ./services/client
           dockerfile: Dockerfile
    volumes:
          - type: bind
            source: ./images_fichas
            target: /app/static/images_250ppi
            volume:
                    nocopy: True
    ports:
        - 3007:3000
    depends_on:
        - users
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/app/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

        #volumes:
 #  - client_volume: /root/todosidentificados/services/client
