"""Set UNIQUE constraint on users.username and users.email

Revision ID: ed11385cbe63
Revises:
Create Date: 2019-06-16 17:11:38.343341

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "ed11385cbe63"
down_revision = "9cf20abce943"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["username"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
