"""Add password column to `users` table

Revision ID: edfbc851c9c6
Revises: ed11385cbe63
Create Date: 2019-06-24 10:59:08.184482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edfbc851c9c6"
down_revision = "ed11385cbe63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=255)))
    op.execute("UPDATE users SET password=email")
    op.alter_column("users", "password", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
